# Database URL, Username, and Password
spring.datasource.url=jdbc:postgresql://postgres:5432/your_db_name
spring.datasource.username=schedule_srv
spring.datasource.password=secret

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
